### ISSUE TITLE
다음 멘토링 일정

### ISSUE THREAD

**Issue by Jun0zo** [osamhack2022/WEB_CLOUD_OhmilZomil_NAVYeffect#23]
언제로 하지 언제로 하지

**Comment by Namhoon-Cho** [comment]
첫 멘토링 날짜 및 보고 내용에 관해 지난 회의 때 이야기했듯 0928 저녁에 회의할 예정, 다음 날 카카오톡으로 멘토님께 연락드릴 예정입니다. 오늘 저녁에 만납시다.
 (대다수 당직병이라서 금토일 중 저녁 시간대가 가능하다 저번주 첫 인사때 미리 양해를 구했기 때문에)

**Comment by Jun0zo** [comment]
10월 4일 멘토링하는 것으로 결정났습니다
